//
// Generated file, do not edit! Created by nedtool 5.4 from child.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CHILD_M_H
#define __CHILD_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>child.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message Child
 * {
 *     int waitingThreshold;
 * }
 * </pre>
 */
class Child : public ::omnetpp::cMessage
{
  protected:
    int waitingThreshold;

  private:
    void copy(const Child& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Child&);

  public:
    Child(const char *name=nullptr, short kind=0);
    Child(const Child& other);
    virtual ~Child();
    Child& operator=(const Child& other);
    virtual Child *dup() const override {return new Child(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getWaitingThreshold() const;
    virtual void setWaitingThreshold(int waitingThreshold);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Child& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Child& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CHILD_M_H

