//
// Generated file, do not edit! Created by nedtool 5.4 from childrenInQueue.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CHILDRENINQUEUE_M_H
#define __CHILDRENINQUEUE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>childrenInQueue.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message ChildrenInQueue
 * {
 *     int number;
 * }
 * </pre>
 */
class ChildrenInQueue : public ::omnetpp::cMessage
{
  protected:
    int number;

  private:
    void copy(const ChildrenInQueue& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ChildrenInQueue&);

  public:
    ChildrenInQueue(const char *name=nullptr, short kind=0);
    ChildrenInQueue(const ChildrenInQueue& other);
    virtual ~ChildrenInQueue();
    ChildrenInQueue& operator=(const ChildrenInQueue& other);
    virtual ChildrenInQueue *dup() const override {return new ChildrenInQueue(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getNumber() const;
    virtual void setNumber(int number);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ChildrenInQueue& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ChildrenInQueue& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CHILDRENINQUEUE_M_H

